# Generated by Django 5.1.4 on 2025-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='defeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tournaments_participated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tournaments_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='victories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
